services:
  ############################
  ##  THIRD PARTY SERVICES  ##
  ############################

  postgres:
    container_name: estate_code_postgres
    image: postgres:15-alpine
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - estate_code_postgres_data:/var/lib/postgresql/data
      - ./local-configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: estate_code_redis
    image: redis:7.4-alpine
    ports:
      - "7380:6379"
    restart: always

  #####################################
  ## ESTATE CODE APP NATIVE SERVICES ##
  #####################################

  cache-service:
    container_name: cache-service
    depends_on:
      - redis
    build:
      context: .
      dockerfile: services/cache_service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9031",
        "--reload",
      ]
    volumes:
      - ./services/cache_service/app:/src/service/app
    env_file:
      - ./services/cache_service/.env.secrets
      - ./services/cache_service/.env.localdocker
    ports:
      - "9031:9031"

  notification-service:
    container_name: notification-service
    depends_on:
      - db-service
    build:
      context: .
      dockerfile: services/notification_service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9035",
        "--reload",
      ]
    volumes:
      - ./services/notification_service/app:/src/service/app
      - ./shared/gatepass_auth:/shared/gatepass_auth
    env_file:
      - ./services/notification_service/.env.secrets
      - ./services/notification_service/.env.localdocker
    ports:
      - "9035:9035"

  code-service:
    container_name: code-service
    depends_on:
      - cache-service
      - db-service
      - notification-service
    build:
      context: .
      dockerfile: services/code_service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9033",
        "--reload",
      ]
    volumes:
      - ./services/code_service/app:/src/service/app
      - ./shared/gatepass_auth:/shared/gatepass_auth
    env_file:
      - ./services/code_service/.env.secrets
      - ./services/code_service/.env.localdocker
    ports:
      - "9033:9033"

  user-profile-service:
    container_name: user-profile-service
    depends_on:
      - db-service
      - notification-service
    build:
      context: .
      dockerfile: services/user_profile_service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9034",
        "--reload",
      ]
    volumes:
      - ./services/user_profile_service/app:/src/service/app
      - ./shared/gatepass_auth:/shared/gatepass_auth
      - ./shared/gatepass_docs:/shared/gatepass_docs
    env_file:
      - ./services/user_profile_service/.env.secrets
      - ./services/user_profile_service/.env.localdocker
    ports:
      - "9034:9034"

  ai-service:
    container_name: ai-service
    depends_on:
      - db-service
    build:
      context: .
      dockerfile: services/ai_service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9036",
        "--reload",
      ]
    volumes:
      - ./services/ai_service/app:/src/service/app
      - ./shared/gatepass_auth:/shared/gatepass_auth
    env_file:
      - ./services/ai_service/.env.secrets
      - ./services/ai_service/.env.localdocker
    ports:
      - "9036:9036"

  db-service:
    container_name: db-service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: services/db-service/Dockerfile
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "9032",
        "--reload",
      ]
    volumes:
      - ./services/db-service/app:/src/service/app
      - ./services/db-service/alembic:/src/service/alembic
      - ./shared/gatepass_docs:/shared/gatepass_docs
      - ./services/db-service/secrets:/var/secrets/gcs:ro
    env_file:
      - ./services/db-service/.env.secrets
      - ./services/db-service/.env.localdocker
    ports:
      - "9032:9032"

  db-migration:
    container_name: db-migration
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: services/db-service/Dockerfile
    env_file:
      - ./services/db-service/.env.secrets
    command: ["alembic", "upgrade", "head"]
    restart: "no"

volumes:
  estate_code_postgres_data:
    name: estate_code_postgres_data
